"""create proposals table

Revision ID: c424a8b3fb14
Revises: 
Create Date: 2026-07-27 20:41:35.247987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c424a8b3fb14'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_name', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('budget_usd', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposals_category'), 'proposals', ['category'], unique=False)
    op.create_index(op.f('ix_proposals_country'), 'proposals', ['country'], unique=False)
    op.create_index(op.f('ix_proposals_deleted_at'), 'proposals', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proposals_deleted_at'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_country'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_category'), table_name='proposals')
    op.drop_table('proposals')
    # ### end Alembic commands ###
